# Generated by Django 3.2 on 2021-05-03 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0006_auto_20160501_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Нийтлэгч'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Image',
            field=models.ImageField(upload_to='news/%Y/%m/%d/', verbose_name='Зураг'),
        ),
    ]
