# Generated by Django 3.2 on 2021-05-03 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registration', '0025_auto_20160522_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='State_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.state', verbose_name='Хот/Аймаг'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='Status_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.status', verbose_name='Төлөв'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='SubState_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_substate', to='registration.substate', verbose_name='Дүүрэг/Сум'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='To_State_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_state', to='registration.state', verbose_name='Хот/Аймаг'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='To_SubState_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='to_substate', to='registration.substate', verbose_name='Дүүрэг/Сум'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='User',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Хэрэглэгч'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Хэрэглэгч'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Delivery_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.delivery', verbose_name='Хүргэлтийн дугаар'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='Type_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.type', verbose_name='Ачааны төрөл'),
        ),
        migrations.AlterField(
            model_name='substate',
            name='State_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='registration.state', verbose_name='Хот/Аймаг'),
        ),
    ]
